#Site settings
title: Rachel M Fisher
email: fisher.rachel.m@outlook.com
author: Rachel M Fisher
description:
baseurl: ""
url: http://elenaltarien.github.io/rachel-m-fisher

# Build settings
permalink: :title/
sass:
  sass_dir: css
markdown: kramdown
highlighter: rouge

# Social icons
show_social_icons: true
github_username: Elenaltarien
twitter_username: RachelMFisher

# Plugins
plugins: [jekyll-paginate]
paginate: 3
